### ISSUE TITLE
Why to npm

### ISSUE THREAD

**Issue by baboon-king** [iconify/api.js#10]
Just want to know 🧐. 
Maybe "pnpm" has some problems.
https://github.com/iconify/api.js/commit/c8d140cb92218c9d7f7b5a9448ee5bd6126ecac6

**Comment by baboon-king** [comment]
I s！
sorry😭
I was too careless

**Comment by cyberalien** [comment]
For this repo pnpm doesn't really make any difference. I'm using it in dev since it saves a lot of space by removing duplication and is much faster to install/update, but no actual features are used. So any package manager will do.

Since this package is meant to run on servers with lots of various architectures, and one pnpm is failing to install on at least one of them, switched to proven package manager.

**Comment by baboon-king** [comment]
Thanks for your reply again. I've got it at https://github.com/iconify/api.js/pull/9 and https://github.com/iconify/api.js/issues/7
